# AutoDock-Vina-Docker
# https://github.com/Metaphorme/AutoDock-Vina-Docker
# MIT License
# Copyright (c) 2022 Metaphorme <https://github.com/Metaphorme>


FROM ubuntu:latest as builder

ARG BRANCHES

RUN /bin/bash -c " \
    set -ex \
    && apt-get update; apt-get install -y swig curl build-essential git libboost-all-dev \
    && git clone -b $BRANCHES https://github.com/ccsb-scripps/AutoDock-Vina /app/AutoDock-Vina \
    && cd /app/AutoDock-Vina/build/linux/release; make \
    "


FROM continuumio/miniconda3:latest

LABEL org.opencontainers.image.authors="Metaphorme" \
      org.opencontainers.image.document="https://github.com/Metaphorme/AutoDock-Vina-Docker" \
      org.opencontainers.image.description="Build from ${BRANCHES}" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.name="vina-python"

COPY --from=builder /app/AutoDock-Vina /opt/AutoDock-Vina

VOLUME /data

RUN /bin/bash -c " \
    set -ex \
    && apt-get update; apt-get install -y curl vim libgomp1 \
    && conda create -n vina python=3 \
    && source /root/.bashrc; conda activate vina \
    && conda config --env --add channels conda-forge \
    && conda install -c conda-forge numpy boost-cpp swig openbabel scipy; pip --no-cache-dir install meeko rdkit pandas \
    && sed -i 's/base/vina/g' /root/.bashrc \
    && cd /opt/AutoDock-Vina/build/python; python setup.py build install \
    && conda clean --all; rm -rf /tmp/* \
    "

ENV PATH=$PATH:/opt/AutoDock-Vina/build/linux/release/:/data/

WORKDIR /data
