# AutoDock-Vina-Docker
# https://github.com/Metaphorme/AutoDock-Vina-Docker
# MIT License
# Copyright (c) 2022 Metaphorme <https://github.com/Metaphorme>


FROM ubuntu:latest as builder

ARG BRANCHES

RUN /bin/bash -c " \
    set -ex \
    && apt-get update; apt-get install -y swig curl build-essential git libboost-all-dev \
    && git clone -b $BRANCHES https://github.com/ccsb-scripps/AutoDock-Vina /app/AutoDock-Vina \
    && cd /app/AutoDock-Vina/build/linux/release; make \
    "

FROM scratch

LABEL org.opencontainers.image.authors="Metaphorme" \
      org.opencontainers.image.document="https://github.com/Metaphorme/AutoDock-Vina-Docker" \
      org.opencontainers.image.description="Build from ${BRANCHES}" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.name="vina"

COPY --from=builder /app/AutoDock-Vina/build/linux/release/vina /

VOLUME /data

WORKDIR /data

ENV PATH=$PATH:/opt/AutoDock-Vina/build/linux/release/:/data/

ENTRYPOINT ["/vina"]
