name: Build AutoDock Image on Develop Branch

on:
  push:
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
      - '.github/*'
      - 'Dockerfile-mgltools'

  workflow_dispatch:

  repository_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build and Release vina images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCHES=develop
          file: Dockerfile-vina
          tags: ghcr.io/metaphorme/vina:develop
          push: true

      - name: Build and Release vina-python images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCHES=develop
          file: Dockerfile-vina-python
          tags: ghcr.io/metaphorme/vina-python:develop
          push: true
      
      - name: Build and Release vina-all images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          build-args: |
            BRANCHES=develop
          file: Dockerfile-vina-all
          tags: ghcr.io/metaphorme/vina-all:develop
          push: true
