name: Build AutoDock Image from Tag

on:
  push:
    paths: 
      - 'Dockerfile-vina'
      - 'Dockerfile-vina-all'
      - 'Dockerfile-vina-python'

  workflow_dispatch:
    inputs:
      Tag:
        description: 'Tag to build'
        required: true
        default: 'v1.2.5'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build and Release vina images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCHES=${{ github.event.inputs.Tag }}
          file: Dockerfile-vina
          tags: ghcr.io/metaphorme/vina:${{ github.event.inputs.Tag }}
          push: true

      - name: Build and Release vina-python images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCHES=${{ github.event.inputs.Tag }}
          file: Dockerfile-vina-python
          tags: ghcr.io/metaphorme/vina-python:${{ github.event.inputs.Tag }}
          push: true
      
      - name: Build and Release vina-all images
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          build-args: |
            BRANCHES=${{ github.event.inputs.Tag }}
          file: Dockerfile-vina-all
          tags: ghcr.io/metaphorme/vina-all:${{ github.event.inputs.Tag }}
          push: true
