name: Build

on:
  push:
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
      - '.github/*'

  workflow_dispatch:

  repository_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BRANCHES: [develop, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build and Release vina images
        uses: docker/build-push-action@v3
        if: ${{ github.event.client_payload.BEANCHES }} == ${{ matrix.BRANCHES }} || github.event.action == ''
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCHES=${{ matrix.BRANCHES }}
          file: Dockerfile-vina
          tags: ghcr.io/metaphorme/vina:${{ matrix.BRANCHES }}
          push: true

      - name: Build and Release vina-python images
        uses: docker/build-push-action@v3
        if: ${{ github.event.client_payload.BEANCHES }} == ${{ matrix.BRANCHES }} || github.event.action == ''
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCHES=${{ matrix.BRANCHES }}
          file: Dockerfile-vina-python
          tags: ghcr.io/metaphorme/vina-python:${{ matrix.BRANCHES }}
          push: true
      
      - name: Build and Release vina-all images
        uses: docker/build-push-action@v3
        if: ${{ github.event.client_payload.BEANCHES }} == ${{ matrix.BRANCHES }} || github.event.action == ''
        with:
          platforms: linux/amd64
          build-args: |
            BRANCHES=${{ matrix.BRANCHES }}
          file: Dockerfile-vina-all
          tags: ghcr.io/metaphorme/vina-all:${{ matrix.BRANCHES }}
          push: true

      - name: Build and Release mgltools images
        uses: docker/build-push-action@v3
        if: ${{ github.event.client_payload.BEANCHES }} == ${{ matrix.BRANCHES }} || github.event.action == ''
        with:
          platforms: linux/amd64
          file: Dockerfile-mgltools
          tags: ghcr.io/metaphorme/mgltools
          push: true
